services:
  app:
    image: tak-manager:1.0.0  # lowercase for Docker compatibility
    container_name: tak-manager-production
    restart: unless-stopped
    environment:
      - TAK_SERVER_INSTALL_DIR=${TAK_SERVER_INSTALL_DIR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TAK_SERVER_INSTALL_DIR}/tak-manager/data:/home/tak-manager:rw
      - ${TAK_SERVER_INSTALL_DIR}/tak-manager/logs:/app/logs:rw
    ports:
      - "8989:8989"
    networks:
      - tak-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tak-manager-network:
    driver: bridge
