services:
  app:
    image: tak-manager:1.1.0
    container_name: tak-manager-production
    restart: unless-stopped
    environment:
      - TAK_SERVER_INSTALL_DIR=${TAK_SERVER_INSTALL_DIR}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TAK_SERVER_INSTALL_DIR}/tak-manager/data:/home/tak-manager:rw
      - ${TAK_SERVER_INSTALL_DIR}/tak-manager/logs:/app/logs:rw
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - tak-manager-network
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:${BACKEND_PORT}/health
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  tak-manager-network:
    driver: bridge
