services:
  app:
    image: tak-manager:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tak-manager-${MODE}
    restart: ${RESTART_POLICY}
    env_file: .env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs:rw
      - ./server:/app/server:rw
      - ./client:/app/client:rw
      - node_modules:/app/client/node_modules
      - /proc:/host/proc:ro
      - ${TAK_SERVER_INSTALL_DIR}:/home/tak-manager:rw
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      ## Add in dev mode - "5174:5174"
    networks:
      - tak-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  tak-manager-network:
    driver: bridge

volumes:
  node_modules: 